name: deploy

on:
  push:
#    tags:
#      - '*'

env:
  SRC_DIR: zxlive

jobs:
  build_and_deploy:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ 3.10 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run:
          pip install .
      - name: Build ZXLive
        run: pyside6-deploy -c pysidedeploy.spec -f
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: build/*
